---
site_name: "Zebrafish Toxicology Atlas Schema Documentation"
theme:
  name: material
  palette:
    scheme: black
    primary: black
  logo: images/biolink-logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Overview: index.md
  - Harmonizer: harmonizer.html
site_url: https://sierra-moxon.github.io/zebrafish-toxicology-atlas-schema
repo_url: https://github.com/sierra-moxon/zebrafish-toxicology-atlas-schema
extra_css:
  - style.css
extra:
  analytics:
    provider: google
    property: G-J23SCD6JB8

